controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

search_course:
    path: /admin/{idA}/search-course
    controller: 'App\Controller\CourseController::search'
    methods: ['GET']



search_user:
    path: /admin/{idA}/search_user
    controller: 'App\Controller\UserController::search'
    methods: ['GET']

# download_userlesson:
#     path: 'student/{idS}/course/{courseId}/lesson/{id}/download'
#     controller: 'App\Controller\YourController::downloadLesson'
#     methods: ['GET']
